# Funciones

#Función exclusiva para la opción 1 - Condicionales
def mostrar_condicionales():
	print("--------------------------------------------")	
	print(" Bienvenidos a la sección de Condicionales")
	print("--------------------------------------------")
	while True:
		print("Que desea ver? \n1- Condicional Simple \n2- Condicional alternativo \n3- Condicional Multiple \n4- Salir")
		op = input("Ingrese:\t")
		if op == "1":
			print("--------------------------------------------")
			print("            Condicional Simple")
			print("--------------------------------------------")
			print("Estructura:")
			print("if (condición):")
			print("   sentencias")
			print("-------------------------------------------------------------------------------")
			print("La sentencia if se ejecuta siempre que la expresión que comprueba devuelve True")
			print("-------------------------------------------------------------------------------")
			print("Ejemplo:")
			print("if True: # equivale a if not False")
			print("    print(''Se cumple la condición'')")
			print("Resultado")
			print("Se cumple la condición")
			print("--------------------------------------------")
			print("             Ejemplo práctico")
			print("--------------------------------------------")
			while True:
				x = int(input("Ingrese un número\t"))
				y = int(input("Ingrese otro número\t"))
				print("Si el primer número es mayor que el segundo, se va a ejecutar el print")
				print("Resultado")
				if x > y:
					print(f"{x} es mayor que {y}")
				print("Desea repetir la prueba? s o n")
				c = input("Ingrese:\t")
				if c == "n":
					break
			print("--------------------------------------------")		
			print("    Muchas gracias por leer esta sección!")
			print("--------------------------------------------")
		elif op == "2":
			print("--------------------------------------------")
			print("            Condicional alternativo")
			print("--------------------------------------------")
			print("Estructura:")
			print("if (condición):")
			print("   sentencias 1")
			print("else:")
			print("   sentencias 2")
			print("-------------------------------------------------------------------------------")
			print("La sentencia if se ejecuta siempre que la expresión que comprueba devuelve True")
			print("Si no lo hace, se ejecuta otro conjuntos de instrucciones dentro del else")
			print("-------------------------------------------------------------------------------")
			print("Ejemplo 1:")
			print("if True: # equivale a if not False")
			print("    print(''Se cumple la condición'')")
			print("else:")
			print("    print(''No se cumple la condición''")
			print("Resultado")
			print("Se cumple la condición")
			print("Ejemplo 2:")
			print("if 3 > 4: # equivale a if not False")
			print("    print(''Se cumple la condición'')")
			print("else:")
			print("    print(''No se cumple la condición''")
			print("Resultado")
			print("No se cumple la condición")
			print("--------------------------------------------")
			print("             Ejemplo práctico")
			print("--------------------------------------------")
			while True:
				x = int(input("Ingrese un número\t"))
				y = int(input("Ingrese otro número\t"))
				print("Si el primer número es mayor que el segundo, se va a ejecutar el print")
				print("Si no se ejecuta otro print diferente que está dentro del else")
				print("Resultado")
				if x > y:
					print(f"{x} es mayor que {y}")
				else:
					print(f"{x} es menor o igual a {y}")
				print("Desea repetir la prueba? s o n")
				c = input("Ingrese:\t")
				if c == "n":
					break
			print("--------------------------------------------")		
			print("    Muchas gracias por leer esta sección!")
			print("--------------------------------------------")
		elif op == "3":
			print("--------------------------------------------")
			print("            Condicional Multiple")
			print("--------------------------------------------")
			print("Estructura:")
			print("if (condición 1):")
			print("   sentencias 1")
			print("elif (condicion 2):")
			print("   sentencias 2")
			print("elif (condicion 3):")
			print("   sentencias 3")
			print("-------------------------------------------------------------------------------")
			print("En Python se encadena a un if u otro elif para comprobar múltiples condiciones,")
			print("siempre que las anteriores no se ejecuten")
			print("-------------------------------------------------------------------------------")
			print("Ejemplo 1:")
			print("x = 4")
			print("y = 5")
			print("if x > y: # equivale a if not False")
			print("    print(''x es mayor que y'')")
			print("elif x < y:")
			print("    print(''x es menor que y''")
			print("else:")
			print("    print(''x e y son iguales'')")
			print("Resultado")
			print("x es menor que y")
			print("--------------------------------------------")
			print("             Ejemplo práctico")
			print("--------------------------------------------")
			while True:
				x = int(input("Ingrese un número\t"))
				y = int(input("Ingrese otro número\t"))
				print("Si el primer número es mayor que el segundo, se va a ejecutar el print")
				print("Si no es va por la siguiente pregunta si x es menor que y y se ejecuta el print")
				print("Si no se ejecuta otro print diferente que está dentro del else")
				print("Resultado")
				if x > y:
					print(f"{x} es mayor que {y}")
				elif x < y:
					print(f"{x} es menor que {y}")
				else:
					print(f"{x} es igual a {y}")
				print("Desea repetir la prueba? s o n")
				c = input("Ingrese:\t")
				if c == "n":
					break
			print("--------------------------------------------")		
			print("    Muchas gracias por leer esta sección!")
			print("--------------------------------------------")
		elif op == "4":
			break
	print("--------------------------------------------")	
	print(" Muchas gracias por leer Condicionales")
	print("--------------------------------------------")

#Función exclusiva para la opción 1 - Condicionales
def mostrar_repetitivas():
	print("--------------------------------------------")	
	print(" Bienvenidos a la sección de Repetitivas")
	print("--------------------------------------------")
	while True:
		print("Que desea ver? \n1- While(Mientras) \n2- For(Para) \n3- Salir")
		op = input("Ingrese:\t")
		if op == "1":
			print("--------------------------------------------")
			print("                While(Mientras)")
			print("--------------------------------------------")
			print("Estructura:")
			print("while (condición): #Condicion tiene que ser True, sino no entra al ciclo while")
			print("   sentencias")
			print("----------------------------------------------------------------------------------")
			print("La sentencia while se ejecuta siempre que la expresión que comprueba devuelve True")
			print("----------------------------------------------------------------------------------")
			print("Ejemplo:")
			print("x = 0")
			print("while x != 6: #Mientras la condicion sea verdadera se ejecuta")
			print("    print(f''{x}'')")
			print("    x += 1")
			print("Resultado")
			print("0")
			print("1")
			print("2")
			print("3")
			print("4")
			print("5")
			print("Por qué no ejecuta y muestra 6? --> porque cuando x = 5 imprime y lo siguiente que hace")
			print("es incrementar x por lo que x = 6 ahora, al volver a preguntar en el while ya x no es")
			print("distinto de 6, sino que es igual por lo que la condición es False y sale del while")
			print("--------------------------------------------")
			print("             Ejemplo práctico")
			print("--------------------------------------------")
			while True:
				x = int(input("Ingrese un número\t"))
				print("Este programa va a ejecutar la cantidad de veces que Ud. ingrese")
				print("Resultado")
				c = 0
				while c != x:
					print(c)
					c += 1
				print("Desea repetir la prueba? s o n")
				c = input("Ingrese:\t")
				if c == "n":
					break
			print("--------------------------------------------")		
			print("    Muchas gracias por leer esta sección!")
			print("--------------------------------------------")
		elif op == "2":
			print("--------------------------------------------")
			print("                For(Para)")
			print("--------------------------------------------")
			print("El for tiene muchas formas, estas son algunas")
			print("Estructura 1:")
			print("for variable in range(numero_inicio, numero_final, de_a_cuanto_contar): #Esto se va a ejecutar desde numero_inicio hasta numero_final contando de a 1")
			print("   sentencias")
			print("--------------------------------------------")
			print("Estructura 2:")
			print("for variable in range(len(string)) #Se ejecuta la cantidad de veces igual que el tamaño de un string dado")
			print("    sentencias")
			print("--------------------------------------------")
			print("Estructura 2:")
			print("for variable in lista/diccionario/string/tupla #Esta vez se ejecuta hasta recorrer la estructura dada, y esa variable toma el valor de la estructura una a una")
			print("     sentencias")
			print("---------------------------------------------------------------------------------------------------------------------------------")
			print("La sentencia for se ejecuta siempre, y una cantidad dada por el range o bien dado una estructura de datos lo recorre por completo")
			print("---------------------------------------------------------------------------------------------------------------------------------")
			print("Ejemplo:")
			print("for i in range(6): #Para el número dado en este caso 10 se ejecuta 10 veces ")
			print("    print(f''{i}'')")
			print("Resultado")
			print("0")
			print("1")
			print("2")
			print("3")
			print("4")
			print("5")
			print("Por qué no ejecuta y muestra 6? --> porque el número 6 indica la cantidad de veces a ejecutar, y como comienza en 0, el último número")
			print("a mostrar es el 5")
			print("--------------------------------------------")
			print("             Ejemplo práctico")
			print("--------------------------------------------")
			while True:
				x = int(input("Ingrese un número que va a indicar la cantidad de veces a ejecutar\t"))
				print("Este programa va a ejecutar la cantidad de veces que Ud. ingrese")
				print("Resultado")
				for i in range(x):
					print(i)
				print("Desea repetir la prueba? s o n")
				c = input("Ingrese:\t")
				if c == "n":
					break
			print("--------------------------------------------")		
			print("    Muchas gracias por leer esta sección!")
			print("--------------------------------------------")
		elif op == "3":
			break
		else:
			print("Opción ingresada incorrecta")
	print("--------------------------------------------")	
	print(" Muchas gracias por leer Repetitivas")
	print("--------------------------------------------")



#Función exclusiva para la opción 1 - Condicionales

def suma(numero1, numero2):
	return numero1 + numero2

def mostrar_funciones():
	print("-----------------------------------------------------------------------------------------")	
	print("                         Bienvenidos a la sección de Funciones")
	print("-----------------------------------------------------------------------------------------")
	print("Una función es un fragmento de código con un nombre asociado que realiza una serie de")
	print("tareas y devuelve un valor. A los fragmentos de código que tienen un nombre asociado y no")
	print("devuelven valores se les suele llamar procedimientos.")
	print("-----------------------------------------------------------------------------------------")
	print("Procedimientos: En Python no existen los procedimientos, ya que cuando el programador no") 
	print("especifica un valor de retorno la función devuelve el valor None (nada), equivalente al") 
	print("null de Java.")
	print("-----------------------------------------------------------------------------------------")
	print("El uso de funciones es un componente muy importante del paradigma de la programación")
	print("llamada estructurada, y tiene varias ventajas:")
	print("● Modularización: permite segmentar un programa complejo en una serie de partes o")
	print("módulos más simples, facilitando así la programación y el depurado.")
	print("● Reutilización: permite reutilizar una misma función en distintos programas.")
	print("-----------------------------------------------------------------------------------------")
	print("Sentencia def")
	print("La sentencia def es una definición de función usada para crear funciones definidas por el")
	print("usuario.")
	print("Una definición de función es una sentencia ejecutable. Su ejecución enlaza el nombre de la")
	print("función en el namespace local actual a un objeto función (un envoltorio alrededor del código")
	print("ejecutable para la función). Este objeto función contiene una referencia al namespace local")
	print("como el namespace global para ser usado cuando la función es llamada.")
	print("La definición de la función no ejecuta el cuerpo de la misma; esto es ejecutado solamente")
	print("cuando la función es llamada.")
	print("En Python las funciones se declaran de la siguiente forma:")
	print("def mi_funcion(param1, param2):")
	print(	"print (param1 print param2)")
	print("-----------------------------------------------------------------------------------------")
	print("Ejemplo práctico")
	print("Tengo una función con la siguiente estructura")
	print("def suma(numero1, numero2):")
	print("   return numero1 + numero2")
	print("---Programa Principal---")
	print("print(suma(5,6))")
	print("----Resultado----")
	print("11")
	print("-----------------------------------------------------------------------------------------")
	while True:
		print("Ejemplo real")
		num1 = int(input("Ingrese un número\t"))
		num2 = int(input("Ingrese otro número\t"))
		print("Resultado")
		print(suma(num1,num2))
		print("Ud. solo ve el resultado, pero lo que se hizo es llamar a la función suma, y devolvió")
		print("la suma de los dos numeros ingresados")
		print("Desea repetir la prueba? s o n")
		c = input("Ingrese:\t")
		if c == "n":
			break
	print("--------------------------------------------")	
	print(" Muchas gracias por leer Funciones")
	print("--------------------------------------------")
